mode = 'file'  # [channel,file]
bucket = 'ekstepspeechrecognition-dev'
channel_url = 'https://www.youtube.com/channel/UCIWcrT3URyL9HDyGgSJfnpg/playlists'
match_title_string = ''
reject_title_string = ''
channel_blob_path = 'data/audiotospeech/raw/download/downloaded/hindi/audio'
archive_blob_path = 'archive'
source_name = 'DD_Jharkhand'  # Scraped Data file path(CSV)
batch_num = 5 # keep batch small on free tier
scraped_data_blob_path = "scraped_data"
file_speaker_name_column = "speaker_name"
file_url_name_column = "video_url"
